spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/traffic
    username: traffic
    password: traffic
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
